#!/usr/bin/env python3

import os
import socket


### Defines the protocol to use, TCP in this case.
cli_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)


### IP address and port of the host we will be connecting to.
host = "192.168.10.6"
port = 5555

### This input will be executed by os.system on the remote machine.
cli_msg = input("Enter command to execute on remote machine: ")

os.system("clear")

cli_sock.connect((host,port))

cli_sock.send(cli_msg.encode())

